
name: Push development client app to Heroku

on:
  push:
    branches:
      - develop
    paths:
      - '**'
      - '!apps/**'
      - 'apps/client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME_DEV_CLIENT }}
    - name: Release
      run: git push origin heroku
