
name: Deploy client (prod)

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!.github/workflows'
      - '.github/workflows/deploy-prod-client.yml'
      - '!apps/**'
      - 'apps/client/**'

jobs:

  # test client code
  test-and-build-client:
    # Name the Job
    name: Test Client React App
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    strategy:
      # setup node version
      matrix:
        node-version: [12.x]
      
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2

      # use correct node version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # cache node_modules
      - name: Cache node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # install dependencies
      - name: Install packages
        run: yarn install --frozen-lockfile

      # build local libs
      - name: Build Libs
        run: yarn build:libs

      # test project
      - name: Test project
        run: yarn test
        env:
          CI: true
  
  deploy:
    needs: test-and-build-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # deploy to Netlify
      - name: publish to netlify
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK_CLIENT_PROD }}
